// Materia: Programación I, Paralelo 4
// Autor: LUIS DANIEL PUYAL ARTEAGA
// Carrera del Estudiante: ING. MECATRONICA
// Fecha creación: 12/08/2026
#include <iostream>
using namespace std;
int main(){
int edad;
char sexo [10];
float altura;
cout<<"digite su edad: ";
cin>>edad;
cout<<"digite su sexo: ";
cin>>sexo;
cout<<"digite su altura en metros: ";
cin>>altura;

cout<<"\nEdad: "<<edad;
cout<<"\nSexo: "<<sexo;
cout<<"\nAltura en metros: "<<altura;
return 0;
}